[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
MyModule = '0x20c9b0ea2015803a6e94f976d28f01f52a83086ad03c78269651fa9108ced556'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]